import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Jobpply",
	description: "Generated by create next app",
	icons: "/roundedlogo.png",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} flex flex-col h-full bg-whitesmoke scroll-smooth`}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
