import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: "Jobpply",
	description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className} h-screen w-screen`}>
				<header>
					<Navbar />
				</header>
				{children}
			</body>
		</html>
	);
}
