import {
	allJobRole,
	allExperience,
	allNavTabs,
	topTenJobs,
	hackathonList,
	ourServices,
	Jobs,
} from "./schema";

export const allJobRoleData: allJobRole[] = [
	{
		key: "fd",
		value: "Frontend Developer",
	},
	{
		key: "bd",
		value: "Backend Developer",
	},
	{
		key: "fsd",
		value: "FullStack Developer",
	},
	{
		key: "ad",
		value: "Application Developer",
	},
	{
		key: "se",
		value: "Software Engineer",
	},
	{
		key: "ds",
		value: "Data Science",
	},
];

export const allExperienceData: allExperience[] = [
	{
		key: "0",
		value: "Internship",
	},
	{
		key: "1",
		value: "Entry Level",
	},
	{
		key: "2",
		value: "Mid Level",
	},
	{
		key: "3",
		value: "Senior Level",
	},
	{
		key: "4",
		value: "Management",
	},
	{
		key: "5",
		value: "Director",
	},
];

export const allNavTabsData: allNavTabs[] = [
	{
		keyValue: "home",
		value: "Home",
		route: "/",
	},
	{
		keyValue: "job",
		value: "Jobs",
		route: "/jobs",
	},
	{
		keyValue: "service",
		value: "Service",
		route: "/service",
	},
	{
		keyValue: "about",
		value: "About",
		route: "/about",
	},
	{
		keyValue: "contact",
		value: "Contact",
		route: "/contact",
	},
	{
		keyValue: "postjob",
		value: "Post Job",
		route: "/postjob",
	},
];

export const topTenJobsData: topTenJobs[] = [
	{
		role: "Frontend Developer",
		location: "Hyderabad",
		salary: "10-14",
		company: "Google",
		keywords: ["Fulltime", "Urgent"],
		logoURL: "https://logo.clearbit.com/www.google.com",
	},
	{
		role: "Data Science",
		location: "Gurgaon",
		salary: "8-11",
		company: "Oracle",
		keywords: ["Fulltime", "Urgent"],
		logoURL: "https://logo.clearbit.com/www.oracle.com",
	},
	{
		role: "FullStack Developer",
		location: "Hyderabad",
		salary: "25-30",
		company: "Microsoft",
		keywords: ["Fulltime", "Urgent"],
		logoURL: "https://logo.clearbit.com/www.microsoft.com",
	},
	{
		role: "FullStack Developer",
		location: "Bengaluru",
		salary: "15-18",
		company: "Netflix",
		keywords: ["Fulltime", "Urgent"],
		logoURL: "https://logo.clearbit.com/www.netflix.com",
	},
	{
		role: "Backend Developer",
		location: "Noida",
		salary: "11-15",
		company: "Adobe",
		keywords: ["Fulltime", "Urgent"],
		logoURL: "https://logo.clearbit.com/www.adobe.com",
	},
];

export const hackathonListData: hackathonList[] = [
	{
		title: "Summer Hack 1.0",
		prize: "$300",
		location: "New Delhi, India",
		reg_start: "01 MARCH 2024",
		reg_end: "23 APRIL 2024",
	},
	{
		title: "HackFest'24",
		prize: "$1,440",
		location: "Gorakhpur, India",
		reg_start: "06 APRIL 2024",
		reg_end: "20 APRIL 2024",
	},
	{
		title: "ETHDubai 2024 Hackathon",
		prize: "$25,000",
		location: "Online",
		reg_start: "19 MARCH 2024",
		reg_end: "21 APRIL 2024",
	},
	{
		title: "Summer Hack 1.0",
		prize: "$300",
		location: "New Delhi, India",
		reg_start: "01 MARCH 2024",
		reg_end: "23 APRIL 2024",
	},
	{
		title: "Hacknology 2024",
		prize: "$300",
		location: "Online",
		reg_start: "11 APRIL 2024",
		reg_end: "22 APRIL 2024",
	},
	{
		title: "GLB HACKATHON 3.O",
		prize: "$603",
		location: "Greater Noida, India",
		reg_start: "22 MARCH 2024",
		reg_end: "25 APRIL 2024",
	},
];

export const ourServiceData: ourServices[] = [
	{
		title: "Resume Review Service",
		keywords: [
			"Professional feedback",
			"Optimization",
			"Tailored advice",
			"Increased visibility",
			"Expert insights",
		],
		uni_key: "resumereview",
		route: "resumereview",
	},
	{
		title: "Resume Writing Service",
		keywords: [
			"Professional writing",
			"Customization",
			"Industry-specific",
			"Highlight achievements",
			"ATS Friendly",
		],
		uni_key: "resumewriting",
		route: "resumewriting",
	},
	{
		title: "Interview Preparation Workshops",
		keywords: [
			"Confidence building",
			"Practice",
			"Effective strategies",
			"Mock interviews",
			"Confidence boost",
		],
		uni_key: "interview",
		route: "interview",
	},
	{
		title: "Skill Assessment Tests",
		keywords: [
			"Skill verification",
			"Instant results",
			"Proficiency assessment",
			"Verified skills",
			"Comprehensive library",
		],
		uni_key: "skilltest",
		route: "skilltest",
	},
	{
		title: "Tech Training Courses",
		keywords: [
			"Expert-led",
			"On-demand",
			"Practical lessons",
			"Flexibility",
			"Career advancement",
		],
		uni_key: "techtraining",
		route: "techtraining",
	},
	{
		title: "Freelancer Success Coaching",
		keywords: [
			"Personalized coaching",
			"Goal setting",
			"Lead Generation",
			"Overcoming challenges",
			"Industry success focus",
		],
		uni_key: "freelancercoaching",
		route: "freelancercoaching",
	},
];

export const allJobsData: Jobs[] = [
	{
		logo: "https://logo.clearbit.com/www.google.com",
		role: "Frontend Developer",
		location: "Hyderabad",
		salary: "10-14",
		company: "Google",
		experience: "Entry Level",
		skills: "HTML, CSS, Javascript",
		dateadded: "Today",
		category: "fd",
	},
	{
		logo: "https://logo.clearbit.com/www.oracle.com",
		role: "Data Science",
		location: "Gurgaon",
		salary: "8-11",
		company: "Oracle",
		experience: "Entry Level",
		skills: "Python, R, Machine Learning",
		dateadded: "Today",
		category: "ds",
	},
	{
		logo: "https://logo.clearbit.com/www.microsoft.com",
		role: "FullStack Developer",
		location: "Hyderabad",
		salary: "25-30",
		company: "Microsoft",
		experience: "Entry Level",
		skills: "ReactJS, NodeJS, MongoDB",
		dateadded: "Today",
		category: "fsd",
	},
	{
		logo: "https://logo.clearbit.com/www.netflix.com",
		role: "Database Developer",
		location: "Bengaluru",
		salary: "15-18",
		company: "Netflix",
		experience: "Entry Level",
		skills: "SQL, MongoDB, DBMS",
		dateadded: "Today",
		category: "ds",
	},
	{
		logo: "https://logo.clearbit.com/www.adobe.com",
		role: "Backend Developer",
		location: "Noida",
		salary: "11-15",
		company: "Adobe",
		experience: "Entry Level",
		skills: "Python, NodeJS, Express",
		dateadded: "Today",
		category: "bd",
	},
	{
		logo: "https://logo.clearbit.com/www.linkedin.com",
		role: "Software Engineer",
		location: "Sunnyvale",
		salary: "110-130",
		company: "LinkedIn",
		experience: "Mid Level",
		skills: "Java, Spring Boot, Microservices",
		dateadded: "Today",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.apple.com",
		role: "iOS Developer",
		location: "San Francisco",
		salary: "120-150",
		company: "Apple",
		experience: "Senior Level",
		skills: "Swift, Objective-C, Xcode",
		dateadded: "Yesterday",
		category: "ad",
	},
	{
		logo: "https://logo.clearbit.com/www.amazon.com",
		role: "UX/UI Designer",
		location: "New York",
		salary: "90-110",
		company: "Amazon",
		experience: "Mid Level",
		skills: "Adobe XD, Sketch, Figma",
		dateadded: "Yesterday",
		category: "fd",
	},
	{
		logo: "https://logo.clearbit.com/www.microsoft.com",
		role: "Software Engineer",
		location: "Redmond",
		salary: "110-130",
		company: "Microsoft",
		experience: "Senior Level",
		skills: "C++, C#, .NET",
		dateadded: "Yesterday",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.netflix.com",
		role: "Machine Learning Engineer",
		location: "Los Angeles",
		salary: "150-180",
		company: "Netflix",
		experience: "Senior Level",
		skills: "Python, TensorFlow, Deep Learning",
		dateadded: "Yesterday",
		category: "ds",
	},
	{
		logo: "https://logo.clearbit.com/www.linkedin.com",
		role: "DevOps Engineer",
		location: "San Francisco",
		salary: "120-140",
		company: "LinkedIn",
		experience: "Mid Level",
		skills: "AWS, Docker, Kubernetes",
		dateadded: "Yesterday",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.spotify.com",
		role: "UI/UX Designer",
		location: "Stockholm",
		salary: "80-100",
		company: "Spotify",
		experience: "Mid Level",
		skills: "Adobe XD, Sketch, Figma",
		dateadded: "Yesterday",
		category: "fd",
	},
	{
		logo: "https://logo.clearbit.com/www.netflix.com",
		role: "Software Engineer",
		location: "Los Angeles",
		salary: "100-120",
		company: "Netflix",
		experience: "Mid Level",
		skills: "Java, Spring Boot, Microservices",
		dateadded: "Yesterday",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.google.com",
		role: "Machine Learning Engineer",
		location: "Mountain View",
		salary: "130-150",
		company: "Google",
		experience: "Senior Level",
		skills: "Python, TensorFlow, Deep Learning",
		dateadded: "Yesterday",
		category: "ds",
	},
	{
		logo: "https://logo.clearbit.com/www.amazon.com",
		role: "Cloud Architect",
		location: "Seattle",
		salary: "140-160",
		company: "Amazon",
		experience: "Senior Level",
		skills: "AWS, Azure, GCP",
		dateadded: "Yesterday",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.microsoft.com",
		role: "Product Manager",
		location: "Redmond",
		salary: "150-180",
		company: "Microsoft",
		experience: "Senior Level",
		skills: "Product Management, Agile, Scrum",
		dateadded: "Yesterday",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.facebook.com",
		role: "Data Analyst",
		location: "Menlo Park",
		salary: "90-110",
		company: "Facebook",
		experience: "Mid Level",
		skills: "SQL, Python, Data Visualization",
		dateadded: "Yesterday",
		category: "ds",
	},
	{
		logo: "https://logo.clearbit.com/www.uber.com",
		role: "Backend Engineer",
		location: "San Francisco",
		salary: "130-150",
		company: "Uber",
		experience: "Senior Level",
		skills: "Python, Django, REST API",
		dateadded: "Today",
		category: "bd",
	},
	{
		logo: "https://logo.clearbit.com/www.twitter.com",
		role: "Software Engineer",
		location: "San Francisco",
		salary: "120-140",
		company: "Twitter",
		experience: "Mid Level",
		skills: "Java, Scala, Play Framework",
		dateadded: "Today",
		category: "se",
	},
	{
		logo: "https://logo.clearbit.com/www.spotify.com",
		role: "Full Stack Engineer",
		location: "Stockholm",
		salary: "100-120",
		company: "Spotify",
		experience: "Entry Level",
		skills: "Node.js, React, MongoDB",
		dateadded: "Today",
		category: "fsd",
	},
];
